# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

os: linux
dist: xenial

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
      workspaces:
        create:
          name: coverage
          paths:
            - coverage.xml

    - stage: Testes
      name: "Testes de Qualidade e Seguranca"
      script:
        - sonar-scanner || travis_terminate 1;
      workspaces:
        use: coverage
      addons:
        sonarcloud:
          organization: assisprestes
          token: ${SONAR_TOKEN}

    - stage: Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-assis
        on:
          branch: main

#notifications:
#slack: Colocar Token
# on_success: always
# on_failure: always
